### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by maran** [eventials/go-tus#17]
Hi,

I've made some changes to go-tus to allow the Upload method to receive a channel. This way upload progress can be passed around. The struct for the info looks something like this.

```go
type UploadInfo struct {
	Offset     int64
	TotalSize  int64
	Percentage int64
	Finished   bool
}
```

Is this something you would be willing to merge?

**Comment by alexandrevicenzi** [comment]
Well, it could be added, but first I need to take a look at the code.

You can easily do this without changing the lib. For example:

```go
uploader, err = client.CreateOrResumeUpload(upload)

if err != nil {
	panic(err)
}

for uploader.Offset() < fileSize {
	perc := uploader.Offset() * 100.0 / fileSize
	log.Infof("Uploading status: %2f", perc)

	err = uploader.UploadChunck()

	if err != nil {
		panic(err)
	}
}
```

**Comment by maran** [comment]
I did not consider that, that might be a better solution. I will try it out 👍

**Comment by alexandrevicenzi** [comment]
@maran I still think that it could be added to the lib if done in a good way.

**Comment by maran** [comment]
I will create a PR from what I made so far as a starting point and we can take it from there.

**Comment by fentas** [comment]
@maran did you create a working version of upload progress. Care to share? :+1:

**Comment by maran** [comment]
@fentas  You can check it out here https://github.com/maran/go-tus/

**Comment by alexandrevicenzi** [comment]
@fentas it was implemented by @maran and I merged in #19.

**Comment by fentas** [comment]
Thanks a lot for the quick reply :+1: 
@alexandrevicenzi Is there an example how to implement this? I would like to implement a progress bar (like https://github.com/cheggaaa/pb).

**Comment by alexandrevicenzi** [comment]
@fentas Yes, you can try something like this:

```go
tusClient, _ := tus.NewClient(...)
f, _ := os.Open(...)

upload, err := tus.NewUploadFromFile(f)

if err != nil {
	panic(err)
}

uploader, err = tusClient.CreateOrResumeUpload(upload)

if err != nil {
	panic(err)
}

fi, err := f.Stat()

if err != nil {
	panic(err)
}

fileSize := fi.Size()

for err == nil && uploader.Offset() < fileSize && !uploader.IsAborted() {
	perc := uploader.Offset() * 100.0 / fileSize
	log.Info("Uploading: %2f", perc)

        err = u.uploader.UploadChunck()
}
```
